import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider ,
  SignedOut,
  SignIn,
  SignedIn,
  UserButton,
  SignUpButton
} from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <ClerkProvider> 
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SignedOut>
  <section className="h-screen w-screen flex items-center justify-center">
    <SignIn />
  </section>
</SignedOut>

<SignedIn>
  {/* <UserButton /> */}
  {children}
</SignedIn>

      </body>
    </html>
    </ClerkProvider>
  );
}




// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import {
//   ClerkProvider,
//   SignedOut,
//   SignedIn,
//   SignIn,
//   UserButton,
// } from "@clerk/nextjs";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           {/* When user is signed out */}
//           <SignedOut>
//             <section className="h-screen w-screen flex items-center justify-center bg-gray-50">
//               <SignIn />
//             </section>
//           </SignedOut>

//           {/* When user is signed in */}
//           <SignedIn>
//             <header className="fixed top-4 left-4 z-50">
//               {/* <UserButton /> */}
//               {children}
//             </header>
//             <main className="p-6"></main>
//           </SignedIn>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }


